In [1]:
import numpy as np
from sklearn.decomposition import PCA

In [2]:
data = [[-0.07951900675624138, -0.0748285682810908, -0.040703740206813166],
 [0.016328440756408213, 0.004389490395726725, 0.007666520377164143],
 [-0.0062361137515056925, -0.011994705082681426, -0.000811291405063197],
 [0.014682267264510773, 0.011911646270392484, 0.015667328635023542],
 [0.07028169214636204, 0.055305150187513086, 0.035307926421490055],
 [0.10332016952849882, 0.06707424288733213, 0.0303233037983823],
 [-0.027150928580143063, 0.09716146393786146, 0.05350335812335935],
 [-0.03922886558703782, 0.06794381985570258, 0.0451626407944985],
 [0.09362264425185074, 0.09082825768743655, 0.059282029573952316],
 [0.12050823524757637, 0.09574824302747886, 0.041406367311554115]]

In [3]:
model = PCA()

In [4]:
model.fit(data)

PCA()

In [5]:
model.components_  # the eigenvectors for each component

array([[-0.73975147, -0.60096143, -0.30267658],
       [-0.6717263 ,  0.63322042,  0.38446804],
       [-0.03938947,  0.48772662, -0.87210734]])

In [6]:
model.singular_values_

array([0.24919912, 0.12393621, 0.01653931])

In [7]:
model.explained_variance_ratio_

array([0.79888149, 0.19759948, 0.00351904])

In [8]:
sum(model.explained_variance_ratio_)

1.0000000000000002

In [9]:
import joblib

In [16]:
s = joblib.dump(model, 'tmp.joblib')
s_compressed = joblib.dump(model, 'tmp_compressed.joblib', compress=True)
s

['tmp.joblib']

In [14]:
model2 = joblib.load(s[0])

In [15]:
model2.components_

array([[-0.73975147, -0.60096143, -0.30267658],
       [-0.6717263 ,  0.63322042,  0.38446804],
       [-0.03938947,  0.48772662, -0.87210734]])