In [1]:
import numpy as np
from sklearn.decomposition import PCA

In [2]:
data = [[-0.07951900675624138, -0.0748285682810908, -0.040703740206813166],
 [0.016328440756408213, 0.004389490395726725, 0.007666520377164143],
 [-0.0062361137515056925, -0.011994705082681426, -0.000811291405063197],
 [0.014682267264510773, 0.011911646270392484, 0.015667328635023542],
 [0.07028169214636204, 0.055305150187513086, 0.035307926421490055],
 [0.10332016952849882, 0.06707424288733213, 0.0303233037983823],
 [-0.027150928580143063, 0.09716146393786146, 0.05350335812335935],
 [-0.03922886558703782, 0.06794381985570258, 0.0451626407944985],
 [0.09362264425185074, 0.09082825768743655, 0.059282029573952316],
 [0.12050823524757637, 0.09574824302747886, 0.041406367311554115]]

In [3]:
model = PCA()

In [4]:
model.fit(data)

PCA()

In [5]:
model.components_  # the eigenvectors for each component

array([[-0.73975147, -0.60096143, -0.30267658],
       [-0.6717263 ,  0.63322042,  0.38446804],
       [-0.03938947,  0.48772662, -0.87210734]])

In [6]:
model.singular_values_

array([0.24919912, 0.12393621, 0.01653931])

In [7]:
model.explained_variance_ratio_

array([0.79888149, 0.19759948, 0.00351904])

In [8]:
sum(model.explained_variance_ratio_)

1.0000000000000002

In [9]:
import pickle

In [10]:
s = pickle.dumps(model)
s

b'\x80\x04\x95-\x03\x00\x00\x00\x00\x00\x00\x8c\x1asklearn.decomposition._pca\x94\x8c\x03PCA\x94\x93\x94)\x81\x94}\x94(\x8c\x0cn_components\x94N\x8c\x04copy\x94\x88\x8c\x06whiten\x94\x89\x8c\nsvd_solver\x94\x8c\x04auto\x94\x8c\x03tol\x94G\x00\x00\x00\x00\x00\x00\x00\x00\x8c\x0eiterated_power\x94h\t\x8c\x0crandom_state\x94N\x8c\x0en_features_in_\x94K\x03\x8c\x0f_fit_svd_solver\x94\x8c\x04full\x94\x8c\x05mean_\x94\x8c\x15numpy.core.multiarray\x94\x8c\x0c_reconstruct\x94\x93\x94\x8c\x05numpy\x94\x8c\x07ndarray\x94\x93\x94K\x00\x85\x94C\x01b\x94\x87\x94R\x94(K\x01K\x03\x85\x94h\x14\x8c\x05dtype\x94\x93\x94\x8c\x02f8\x94\x89\x88\x87\x94R\x94(K\x03\x8c\x01<\x94NNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00t\x94b\x89C\x18\x10\xbf\xa3\x96\xfbL\x9b?\xfa\x12\xa7TD\xa9\xa4?\xd5c4\x95\xd4E\x99?\x94t\x94b\x8c\x0fnoise_variance_\x94G\x00\x00\x00\x00\x00\x00\x00\x00\x8c\nn_samples_\x94K\n\x8c\x0bn_features_\x94K\x03\x8c\x0bcomponents_\x94h\x13h\x16K\x00\x85\x94h\x18\x87\x94R\x94(K\x01K\x03K\x03\x86\x94h 

In [11]:
model2 = pickle.loads(s)

In [12]:
model2.components_

array([[-0.73975147, -0.60096143, -0.30267658],
       [-0.6717263 ,  0.63322042,  0.38446804],
       [-0.03938947,  0.48772662, -0.87210734]])

In [13]:
# get result diffs
model.transform(data) - model2.transform(data)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])