In [1]:
from sklearn.decomposition import PCA

In [2]:
data = [[-0.07951900675624138, -0.0748285682810908, -0.040703740206813166],
 [0.016328440756408213, 0.004389490395726725, 0.007666520377164143],
 [-0.0062361137515056925, -0.011994705082681426, -0.000811291405063197],
 [0.014682267264510773, 0.011911646270392484, 0.015667328635023542],
 [0.07028169214636204, 0.055305150187513086, 0.035307926421490055],]

In [3]:
model = PCA()

In [4]:
model.fit(data)

PCA()

In [5]:
model.components_

array([[-0.70240484, -0.61253106, -0.36253709],
       [-0.62349643,  0.28380626,  0.72849585],
       [ 0.34333604, -0.7377396 ,  0.58125782]])

In [6]:
model.singular_values_

array([0.15409567, 0.00707542, 0.00253296])

In [7]:
r1 = model.transform(data)
r1

array([[ 1.18006306e-01, -1.00363450e-03, -1.06025747e-03],
       [-1.53769403e-02, -3.04406087e-03,  1.52091918e-03],
       [ 1.35818618e-02,  1.98870391e-04,  9.33169745e-04],
       [-2.17288039e-02,  5.94571297e-03,  5.68685825e-05],
       [-9.44824232e-02, -2.09688799e-03, -1.45070004e-03]])

In [8]:
# try rebuilding a model from the data in the first model & using it to apply
m2 = PCA()  # can't just pass compents_ etc in on constructor  - gets an erro
m2.components_ = model.components_
m2.singular_values_ = model.singular_values_
m2.mean_ = model.mean_
# don't need explained_varience_ratio in order to apply model (incl anyway?)

In [9]:
r2 = m2.transform(data)
r2

array([[ 1.18006306e-01, -1.00363450e-03, -1.06025747e-03],
       [-1.53769403e-02, -3.04406087e-03,  1.52091918e-03],
       [ 1.35818618e-02,  1.98870391e-04,  9.33169745e-04],
       [-2.17288039e-02,  5.94571297e-03,  5.68685825e-05],
       [-9.44824232e-02, -2.09688799e-03, -1.45070004e-03]])

In [10]:
r1 == r2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [11]:
model.mean_

array([ 0.00310746, -0.0030434 ,  0.00342535])

In [12]:
import numpy as np
np.mean(data, axis=0)

array([ 0.00310746, -0.0030434 ,  0.00342535])

In [13]:
import pandas as pd

In [16]:
df = pd.DataFrame(data)
df

0         1         2
0 -0.079519 -0.074829 -0.040704
1  0.016328  0.004389  0.007667
2 -0.006236 -0.011995 -0.000811
3  0.014682  0.011912  0.015667
4  0.070282  0.055305  0.035308

In [ ]:
data2 = [
    [0.071022384345370282,-0.0018848835004448006,-0.069137500844925481],
    [0.035278308193234964,-0.0018789385152055971,-0.033399369678029367],
    [-0.13173740306613141,0.085062984385466833,0.046674418680664576],
    [-0.1267030117762783,0.10048975661686194,0.02621325515941636],
    [0.080874675786664629,-0.017307704523854439,-0.06356697126281019],
    [0.048195672517894916,-0.014017709482924023,-0.034177963034970948],
    [0.020080315883924615,-0.021350924828184903,0.0012706089442602875],
    [0.021096566842135511,-0.031614018128334753,0.010517451286199298],
    [0.03699436538881623,-0.02891331137672537,-0.00808105401209086],
    [-0.055101874115630944,-0.0685852506466551,0.123687124762286]]